source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.8'
pod 'SDWebImage', '~>3.6'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'